export const elementsLocation = {
  vaultName: document.querySelector('.vault-name'),
  loginButton: document.querySelector('.login-button'),
  registerButton: document.querySelector('.register-button'),
  welcomeText: document.querySelector('.welcome-text'),
  footer: document.querySelector('.footer-text'),
  registerForm: document.querySelector('.register-form'),
  loginForm: document.querySelector('.login-form'),
  registerSubmit: document.querySelector('.submit-register-button'),
  loginSubmit: document.querySelector('.submit-login-button'),
  specialNameGreeting: document.querySelector('.special-name-greeting'),
  specialRemember: document.querySelector('.special-remember'),
  specialRemainingNumber: document.querySelector('.special-remaining'),
  specialForm: document.querySelector('.special-form'),
  specialSubmit: document.querySelector('.submit-special'),
  navbarElements: document.querySelector('.nav-elements'),
  registerName: document.querySelector('#register-name'),
  registerPassword: document.querySelector('#password-register'),
  registerPasswordConfirm: document.querySelector('#confirm-password-register'),
};

export const iconsLocation = {
  strengthMinusIcon: document.querySelector('.strength-minus'),
  strengthPlusIcon: document.querySelector('.strength-plus'),
  perceptionMinusIcon: document.querySelector('.perception-minus'),
  perceptionPlusIcon: document.querySelector('.perception-plus'),
  enduranceMinusIcon: document.querySelector('.endurance-minus'),
  endurancePlusIcon: document.querySelector('.endurance-plus'),
  charismaMinusIcon: document.querySelector('.charisma-minus'),
  charismaPlusIcon: document.querySelector('.charisma-plus'),
  intelligenceMinusIcon: document.querySelector('.intelligence-minus'),
  intelligencePlusIcon: document.querySelector('.intelligence-plus'),
  agilityMinusIcon: document.querySelector('.agility-minus'),
  agilityPlusIcon: document.querySelector('.agility-plus'),
  luckMinusIcon: document.querySelector('.luck-minus'),
  luckPlusIcon: document.querySelector('.luck-plus'),
};

export const specialInputsLocation = {
  strengthInput: document.getElementById('strength'),
  perceptionInput: document.getElementById('perception'),
  enduranceInput: document.getElementById('endurance'),
  charismaInput: document.getElementById('charisma'),
  intelligenceInput: document.getElementById('intelligence'),
  agilityInput: document.getElementById('agility'),
  luckInput: document.getElementById('luck'),
};
